# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='hit_f',
            new_name='hits_f',
        ),
    ]
