# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170917_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='goals_a_sa',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='goals_f_sa',
        ),
    ]
