# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20170918_0248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
