# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goalies',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
