# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalies',
            name='id',
        ),
        migrations.AddField(
            model_name='goalies',
            name='player',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='goalies',
            name='player_id',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='goalies',
            name='game_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='season',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='team',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='goalies',
            name='opponent',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='goalies',
            name='home',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='goalies',
            name='strength',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='goalies',
            name='shots_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='goals_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='fenwick_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='corsi_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='toi_on',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='toi_off',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='shots_a_sa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='goals_a_sa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='fenwick_a_sa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='corsi_a_sa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='goalies',
            name='primary_key',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),

    ]
