# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalies', '0003_remove_goalies_goals_a_sa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goalies',
        ),
    ]
