# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goalies', '0004_delete_goalies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goalies',
            fields=[
                ('player', models.CharField(default='', max_length=30)),
                ('player_id', models.CharField(default='', max_length=7)),
                ('game_id', models.IntegerField(null=True)),
                ('season', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('team', models.CharField(default='', max_length=3)),
                ('opponent', models.CharField(default='', max_length=3)),
                ('home', models.CharField(default='', max_length=3)),
                ('strength', models.CharField(default='', max_length=3)),
                ('shots_a', models.IntegerField(null=True)),
                ('goals_a', models.IntegerField(null=True)),
                ('fenwick_a', models.IntegerField(null=True)),
                ('corsi_a', models.IntegerField(null=True)),
                ('toi_on', models.IntegerField(null=True)),
                ('toi_off', models.IntegerField(null=True)),
                ('shots_a_sa', models.FloatField(null=True)),
                ('fenwick_a_sa', models.FloatField(null=True)),
                ('corsi_a_sa', models.FloatField(null=True)),
                ('if_empty', models.IntegerField(null=True)),
                ('primary_key', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
