# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skaters',
            fields=[
                ('player', models.CharField(default='', max_length=30)),
                ('player_id', models.CharField(default='', max_length=7)),
                ('position', models.CharField(default='', max_length=3)),
                ('season', models.IntegerField(null=True)),
                ('game_id', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('team', models.CharField(default='', max_length=3)),
                ('opponent', models.CharField(default='', max_length=3)),
                ('home', models.CharField(default='', max_length=3)),
                ('strength', models.CharField(default='', max_length=3)),
                ('toi_on', models.IntegerField(null=True)),
                ('goals', models.IntegerField(null=True)),
                ('a1', models.IntegerField(null=True)),
                ('a2', models.IntegerField(null=True)),
                ('isf', models.IntegerField(null=True)),
                ('ifen', models.IntegerField(null=True)),
                ('icors', models.IntegerField(null=True)),
                ('iblocks', models.IntegerField(null=True)),
                ('pen_drawn', models.IntegerField(null=True)),
                ('pen_taken', models.IntegerField(null=True)),
                ('gives', models.IntegerField(null=True)),
                ('takes', models.IntegerField(null=True)),
                ('hits_f', models.IntegerField(null=True)),
                ('hits_a', models.IntegerField(null=True)),
                ('ifac_win', models.IntegerField(null=True)),
                ('ifac_loss', models.IntegerField(null=True)),
                ('shots_f', models.IntegerField(null=True)),
                ('goals_f', models.IntegerField(null=True)),
                ('fenwick_f', models.IntegerField(null=True)),
                ('corsi_f', models.IntegerField(null=True)),
                ('shots_a', models.IntegerField(null=True)),
                ('goals_a', models.IntegerField(null=True)),
                ('fenwick_a', models.IntegerField(null=True)),
                ('corsi_a', models.IntegerField(null=True)),
                ('shots_f_sa', models.FloatField(null=True)),
                ('fenwick_f_sa', models.FloatField(null=True)),
                ('corsi_f_sa', models.FloatField(null=True)),
                ('shots_a_sa', models.FloatField(null=True)),
                ('fenwick_a_sa', models.FloatField(null=True)),
                ('corsi_a_sa', models.FloatField(null=True)),
                ('face_off', models.IntegerField(null=True)),
                ('face_def', models.IntegerField(null=True)),
                ('face_neu', models.IntegerField(null=True)),
                ('toi_off', models.IntegerField(null=True)),
                ('shots_f_off', models.IntegerField(null=True)),
                ('goals_f_off', models.IntegerField(null=True)),
                ('fenwick_f_off', models.IntegerField(null=True)),
                ('corsi_f_off', models.IntegerField(null=True)),
                ('shots_a_off', models.IntegerField(null=True)),
                ('goals_a_off', models.IntegerField(null=True)),
                ('fenwick_a_off', models.IntegerField(null=True)),
                ('corsi_a_off', models.IntegerField(null=True)),
                ('shots_f_off_sa', models.FloatField(null=True)),
                ('fenwick_f_off_sa', models.FloatField(null=True)),
                ('corsi_f_off_sa', models.FloatField(null=True)),
                ('shots_a_off_sa', models.FloatField(null=True)),
                ('fenwick_a_off_sa', models.FloatField(null=True)),
                ('corsi_a_off_sa', models.FloatField(null=True)),
                ('face_off_off', models.IntegerField(null=True)),
                ('face_neu_off', models.IntegerField(null=True)),
                ('face_def_off', models.IntegerField(null=True)),
                ('primary_key', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
