# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skaters',
            name='position',
            field=models.CharField(default='', max_length=3, null=True),
        ),
    ]
