# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skaters', '0002_auto_20170917_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='skaters',
            name='handedness',
            field=models.CharField(default='', max_length=2, null=True),
        ),
    ]
